### ISSUE TITLE
메뉴바 투명도 때문에 텍스트랑 겹치면 잘 안보임

### ISSUE THREAD

**Issue by ksjae** [newscspace/scspace#13]
반투명 메뉴바에 글씨가 겹치면
<img width="372" alt="image" src="https://user-images.githubusercontent.com/17930170/187842402-b9360f4f-607c-4b29-92c7-9206f4b95925.png">
가독성이 떨어지는 문제가 있습니다

**Comment by uxhif** [comment]
해결
