### ISSUE TITLE
합주실 멘트 오류

### ISSUE THREAD

**Issue by ksjae** [newscspace/scspace#14]
3인일때는 합주실을 쓰라고 해야할까요?
<img width="253" alt="image" src="https://user-images.githubusercontent.com/17930170/187842647-e52b078e-ed1d-497b-b4f7-4a768c9fd298.png">

(가끔 AI인듯한 유기체가 이런거 가지고 뭐라 해서)

**Comment by choisw0823** [comment]
해결
