### ISSUE TITLE
[CSS] 메뉴바랑 내용이랑 겹침

### ISSUE THREAD

**Issue by ksjae** [newscspace/scspace#16]
#13 이랑 연관되어 있으나, 약간 다름

404 에러가
<img width="244" alt="image" src="https://user-images.githubusercontent.com/17930170/187894741-6e720c08-ecb5-48b0-8702-1982687f2da0.png">
이렇게 대충 띄우다 보니 내용쪽이 적으면 저따구로 겹쳐서 안보여요

**Comment by uxhif** [comment]
대충 살면 안돼요? 흑흑

**Comment by uxhif** [comment]
@ksjae 사실 고쳐놨답니다 우하 커밋..해야하는데.....^^
