### ISSUE TITLE
[HTML] 세부 페이지에서 새로고침시 로고 깨짐

### ISSUE THREAD

**Issue by ksjae** [newscspace/scspace#17]
세부 페이지에서 새로고침시 Header에서 상대경로(로 추정되는) 문제로 아래와 같이 로고를 엉뚱한데서 찾고 있습니다

<img width="688" alt="image" src="https://user-images.githubusercontent.com/17930170/187922923-ebc89fdd-299a-4c9a-8b3b-d1f63f080edc.png">

수정은 간단하겠네요

**Comment by uxhif** [comment]
수정완료~!
